/* eslint-disable */
// AUTO-GENERATED by contracts/deploy.sh from contracts/registry.json
// Do not edit by hand.

export const CONTRACTS = {
  "token-locker": {
    testnet: {
      v1: "CBFCKEOQRQIXKLGU4QBUQVOINOKFBOXJ37LXEKLKNUO6TW4FNGDU26AW",
    },
    mainnet: {} as Record<string, string>,
  },
  "lp-locker": {
    testnet: {
      v1: "CA3WYETNIF5IAF3VUNQ3SYKZFV45TOFBF7CEZ46I7QEBPWTRM73WLEI4",
    },
    mainnet: {} as Record<string, string>,
  },
} as const

export type ContractFamily = keyof typeof CONTRACTS
export type ContractEnv = "testnet" | "mainnet"
export type ContractVersion = string

const env = (import.meta.env.VITE_CONTRACT_ENV || "testnet") as ContractEnv
const version = (import.meta.env.VITE_CONTRACT_VERSION || "v1") as ContractVersion

export function getContractAddress(family: ContractFamily): string {
  const addr = (CONTRACTS as any)?.[family]?.[env]?.[version]
  if (!addr || typeof addr !== "string") {
    throw new Error(
      `Contract address not configured for ${family} on ${env}/${version}. Run contracts/deploy.sh to update registry.`,
    )
  }
  return addr
}
