/* eslint-disable */
// AUTO-GENERATED by contracts/deploy.sh from contracts/registry.json
// Do not edit by hand.

export type ContractFamily = "token-locker" | "lp-locker"
export type ContractEnv = "testnet" | "mainnet"
export type ContractVersion = "v1" | "v2" | "v3" | (string & {})

// These are resolved at deploy-time for the selected env/version.
// For local development, you can override via VITE_CONTRACT_ENV and VITE_CONTRACT_VERSION.

const env = (import.meta.env.VITE_CONTRACT_ENV || "testnet") as ContractEnv
const version = (import.meta.env.VITE_CONTRACT_VERSION || "v1") as ContractVersion

// Fallbacks are placeholders until the first deploy updates this file.
export const CONTRACTS: Record<ContractFamily, Record<ContractEnv, Record<string, string>>> = {
    "token-locker": {
        testnet: {
            [version]: "REPLACE_ME",
        },
        mainnet: {
            [version]: "REPLACE_ME",
        },
    },
    "lp-locker": {
        testnet: {
            [version]: "REPLACE_ME",
        },
        mainnet: {
            [version]: "REPLACE_ME",
        },
    },
}

export function getContractAddress(family: ContractFamily): string {
    const addr = CONTRACTS[family]?.[env]?.[version]
    if (!addr || addr === "REPLACE_ME") {
        throw new Error(
            `Contract address not configured for ${family} on ${env}/${version}. Run contracts/deploy.sh to update registry and generated constants.`,
        )
    }
    return addr
}

