#!/usr/bin/env bash
# Deploy both contracts to Stellar and update contracts/registry.json + generated TS constants.
# Usage: ./deploy.sh <your-stellar-account-alias> [network]
#
# Prerequisites:
#   stellar keys generate --global <alias> --network <network>
#   stellar keys fund <alias> --network <network>
#
# Optional env vars:
#   CONTRACT_VERSION_OVERRIDE=v1|v2|...
#   CONTRACT_DEPRECATED_FLAG=true|false
#
set -euo pipefail

ACCOUNT="${1:?Usage: ./deploy.sh <account-alias> [network]}"
NETWORK="${2:-testnet}"

# Allow overriding version/deprecation for repeat deployments.
CONTRACT_VERSION_OVERRIDE="${CONTRACT_VERSION_OVERRIDE:-}"
CONTRACT_DEPRECATED_FLAG="${CONTRACT_DEPRECATED_FLAG:-false}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REGISTRY_PATH="$ROOT_DIR/contracts/registry.json"
GENERATED_TS_PATH="$ROOT_DIR/src/lib/contracts.generated.ts"
WASM_DIR="$ROOT_DIR/contracts/../target/wasm32v1-none/release"

WASM_TOKEN="$WASM_DIR/token_locker.wasm"
WASM_LP="$WASM_DIR/lp_locker.wasm"

require_wasm(){
  local f="$1"
  if [[ ! -f "$f" ]]; then
    echo "ERROR: missing WASM: $f" >&2
    exit 1
  fi
}

ensure_registry(){
  if [[ ! -f "$REGISTRY_PATH" ]]; then
    echo "ERROR: registry not found at $REGISTRY_PATH" >&2
    exit 1
  fi
}

sha256(){
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    openssl dgst -sha256 "$1" | awk '{print $2}'
  fi
}

next_version_for_family(){
  local family="$1" # token-locker|lp-locker
  local env="$2"     # testnet|mainnet

  # Determine next version number by scanning keys v1,v2,...
  # If override is provided, use it.
  if [[ -n "$CONTRACT_VERSION_OVERRIDE" ]]; then
    echo "$CONTRACT_VERSION_OVERRIDE"
    return
  fi

  # Use node to parse JSON reliably.
  node - <<'NODE' "$REGISTRY_PATH" "$family" "$env" 
const fs = require('fs');
const path = process.argv[2];
const family = process.argv[3];
const env = process.argv[4];
const j = JSON.parse(fs.readFileSync(path,'utf8'));
const versionsObj = (j[family] && j[family][env]) ? j[family][env] : {};
const versions = Object.keys(versionsObj).map(v=>v).filter(v=>/^v\d+$/.test(v)).sort((a,b)=>parseInt(a.slice(1))-parseInt(b.slice(1)));
const last = versions.length ? versions[versions.length-1] : null;
if(!last) { console.log('v1'); process.exit(0); }
const n = parseInt(last.slice(1))+1;
console.log('v'+n);
NODE
}

upsert_registry(){
  local family="$1" # token-locker|lp-locker
  local env="$2"     # testnet|mainnet
  local version="$3"
  local address="$4"
  local wasmHash="$5"

  node - <<'NODE' "$REGISTRY_PATH" "$family" "$env" "$version" "$address" "$wasmHash" "$CONTRACT_DEPRECATED_FLAG"
const fs = require('fs');
const path = process.argv[2];
const family = process.argv[3];
const env = process.argv[4];
const version = process.argv[5];
const address = process.argv[6];
const wasmHash = process.argv[7];
const deprecatedFlag = process.argv[8];
const j = JSON.parse(fs.readFileSync(path,'utf8'));

if(!j[family]) j[family] = {};
if(!j[family][env]) j[family][env] = {};
if(!j[family][env][version]) j[family][env][version] = {};

j[family][env][version].address = address;
j[family][env][version].wasmHash = wasmHash;
j[family][env][version].deployedAt = new Date().toISOString();
j[family][env][version].deprecated = String(deprecatedFlag).toLowerCase() === 'true';

fs.writeFileSync(path, JSON.stringify(j, null, 2) + '\n');
NODE
}

generate_constants_from_registry(){
  node - <<'NODE' "$REGISTRY_PATH" "$GENERATED_TS_PATH"
const fs = require('fs');
const registryPath = process.argv[2];
const out = process.argv[3];
const j = JSON.parse(fs.readFileSync(registryPath,'utf8'));

function safeString(s){return String(s).replace(/"/g,'\\"');}

// Emit a simple runtime resolver that reads env/version from VITE.
const content = `/* eslint-disable */\n// AUTO-GENERATED by contracts/deploy.sh\n// Source: contracts/registry.json\n\nexport const CONTRACTS = ${JSON.stringify(j, null, 2)} as const;\n\nexport type ContractFamily = keyof typeof CONTRACTS;\nexport type ContractEnv = keyof typeof CONTRACTS[ContractFamily];\nexport type ContractVersion = string;\n\nconst env = (import.meta.env.VITE_CONTRACT_ENV || "testnet") as ContractEnv;\nconst version = (import.meta.env.VITE_CONTRACT_VERSION || "v1") as ContractVersion;\n\nexport function getContractAddress(family: ContractFamily): string {\n  const addr = (CONTRACTS as any)?.[family]?.[env]?.[version];\n  if (!addr || typeof addr !== 'string' || addr === 'REPLACE_ME') {\n    throw new Error(
      \`Contract address not configured for \${family} on \${String(env)}/\${String(version)}.\nRun contracts/deploy.sh to update registry and constants.\`
    );\n  }\n  return addr;\n}\n`;

// The registry stores { address,deployedAt,wasmHash,deprecated } per version.
// The frontend resolver expects the actual address string.
// Convert in-place for the generated constants.
for (const family of Object.keys(j)){
  for (const env of Object.keys(j[family] || {})){
    for (const ver of Object.keys(j[family][env] || {})){
      j[family][env][ver] = j[family][env][ver].address;
    }
  }
}

const typed = `/* eslint-disable */\n// AUTO-GENERATED by contracts/deploy.sh\n// Source: contracts/registry.json\n\nexport const CONTRACTS = ${JSON.stringify(j, null, 2)} as const;\n\nexport type ContractFamily = keyof typeof CONTRACTS;\nexport type ContractEnv = keyof typeof CONTRACTS[ContractFamily];\nexport type ContractVersion = string;\n\nconst env = (import.meta.env.VITE_CONTRACT_ENV || "testnet") as ContractEnv;\nconst version = (import.meta.env.VITE_CONTRACT_VERSION || "v1") as ContractVersion;\n\nexport function getContractAddress(family: ContractFamily): string {\n  const addr = (CONTRACTS as any)?.[family]?.[env]?.[version];\n  if (!addr || typeof addr !== 'string') {\n    throw new Error(\`Contract address not configured for \${family} on \${String(env)}/\${String(version)}. Run contracts/deploy.sh to update registry.\`);\n  }\n  return addr;\n}\n`;

fs.writeFileSync(out, typed);
NODE
}

validate_build(){
  echo "==> Building contracts WASM..."
  (cd "$ROOT_DIR/contracts" && cargo build --release --target wasm32v1-none)
}

require_wasm "$WASM_TOKEN"
require_wasm "$WASM_LP"

ensure_registry

# Compute contract version entries.
ENV_NETWORK="$NETWORK"
TOKEN_VERSION=$(next_version_for_family "token-locker" "$ENV_NETWORK")
LP_VERSION=$(next_version_for_family "lp-locker" "$ENV_NETWORK")

TOKEN_HASH=$(sha256 "$WASM_TOKEN")
LP_HASH=$(sha256 "$WASM_LP")

# Deploy
echo "==> Deploying token-locker ($TOKEN_VERSION)..."
TOKEN_LOCKER_ID=$(stellar contract deploy \
  --wasm "$WASM_TOKEN" \
  --source "$ACCOUNT" \
  --network "$NETWORK")
echo "    token-locker address: $TOKEN_LOCKER_ID"

echo "==> Deploying lp-locker ($LP_VERSION)..."
LP_LOCKER_ID=$(stellar contract deploy \
  --wasm "$WASM_LP" \
  --source "$ACCOUNT" \
  --network "$NETWORK")
echo "    lp-locker address: $LP_LOCKER_ID"

# Update registry with metadata.
upsert_registry "token-locker" "$ENV_NETWORK" "$TOKEN_VERSION" "$TOKEN_LOCKER_ID" "$TOKEN_HASH"
upsert_registry "lp-locker" "$ENV_NETWORK" "$LP_VERSION" "$LP_HASH"

# Generate constants
generate_constants_from_registry

# Git tag
if command -v git >/dev/null 2>&1; then
  git tag -f "deploy/token-locker-${ENV_NETWORK}-${TOKEN_VERSION}" \
    >/dev/null 2>&1 || true
  git tag -f "deploy/lp-locker-${ENV_NETWORK}-${LP_VERSION}" \
    >/dev/null 2>&1 || true
fi

echo ""
echo "==> Done. Updated:"
echo "    $REGISTRY_PATH"
echo "    $GENERATED_TS_PATH"

echo ""
echo "==> Set these for local overrides if needed:"
echo "    VITE_CONTRACT_ENV=${ENV_NETWORK}"
echo "    VITE_CONTRACT_VERSION=${TOKEN_VERSION} (or ${LP_VERSION})"

